language: python
python:
  - "3.6"

addons:
  sonarcloud:
    # create sonar connection for code health analysis
    organization: "deven96-github" 
    token:
      secure: $SONAR_TOKEN

# Branches to enbale CI.
branches:
  only:
    - master

# Command to install dependencies.
install:
  - pip install -r requirements.txt
  - python setup.py -q install

# Build script (If successfully built - no errors)
script:
  # - pytest
  - python main.py
after_success:
  - ./docs.sh
  - sonar-scanner

deploy:
  provider: pypi
  user: "deven96"
  password: $PYPI_PASSWORD
  all_branches: true
  condition: $TRAVIS_TAG =~ ^v[0-9]+\.[0-9]+\.[0-9]+
  skip_existing: true

notifications:
    slack: bisoncorps:urrq42VfAo4zJP2r6lH2dU8Y
