language: python
python:
  - "3.6"

# Branches to enbale CI.
branches:
  only:
    - master

# Command to install dependencies.
install:
  - pip install -r requirements.txt
  - python setup.py -q install

# Build script (If successfully built - no errors)
script:
  # - pytest
  - python main.py
